# Generated by Django 2.0.2 on 2021-06-26 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('url', models.TextField()),
                ('votes_total', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='image/blogimages/')),
                ('icon', models.ImageField(upload_to='image/blogimages/')),
                ('body', models.TextField(max_length=1000)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
