# Generated by Django 2.0.2 on 2021-06-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
